language: node_js

sudo: required
branches:
  only:
  - master

install:
  - npm install

script:
  - npm run-script lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadless
  - npm run-script build --prod
